// Next.config.mjs configuration file
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  typescript: {
    // ⚠️ Temporary — TS errors build ko fail nahi karenge
    ignoreBuildErrors: true,
  },
  eslint: {
    // ⚠️ Temporary — ESLint errors (unescaped entities, etc.) build ko fail nahi karenge
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
    ],
  },
  experimental: {
    optimizePackageImports: ['lucide-react'],
  },
  env: {
    NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
    NEXT_PUBLIC_WS_URL: process.env.NEXT_PUBLIC_WS_URL,
    NEXT_PUBLIC_API_VERSION: process.env.NEXT_PUBLIC_API_VERSION,
    NEXT_PUBLIC_API_TIMEOUT: process.env.NEXT_PUBLIC_API_TIMEOUT,

    NEXT_PUBLIC_API_AUTH_ENDPOINT: process.env.NEXT_PUBLIC_API_AUTH_ENDPOINT,
    NEXT_PUBLIC_REFRESH_TOKEN_ENDPOINT: process.env.NEXT_PUBLIC_REFRESH_TOKEN_ENDPOINT,
    NEXT_PUBLIC_REGISTER_ENDPOINT: process.env.NEXT_PUBLIC_REGISTER_ENDPOINT,
    NEXT_PUBLIC_LOGIN_ENDPOINT: process.env.NEXT_PUBLIC_LOGIN_ENDPOINT,
    NEXT_PUBLIC_PROFILE_ENDPOINT: process.env.NEXT_PUBLIC_PROFILE_ENDPOINT,
    NEXT_PUBLIC_GET_USER_ENDPOINT: process.env.NEXT_PUBLIC_GET_USER_ENDPOINT,
    NEXT_PUBLIC_USERS_ENDPOINT: process.env.NEXT_PUBLIC_USERS_ENDPOINT,
    NEXT_PUBLIC_UPDATE_PROFILE_ENDPOINT: process.env.NEXT_PUBLIC_UPDATE_PROFILE_ENDPOINT,
    NEXT_PUBLIC_LOGOUT_ENDPOINT: process.env.NEXT_PUBLIC_LOGOUT_ENDPOINT,

    NEXT_PUBLIC_PROFILE_PHOTO_ENDPOINT: process.env.NEXT_PUBLIC_PROFILE_PHOTO_ENDPOINT,
    NEXT_PUBLIC_COVER_PHOTO_ENDPOINT: process.env.NEXT_PUBLIC_COVER_PHOTO_ENDPOINT,
    NEXT_PUBLIC_HEADLINE_ENDPOINT: process.env.NEXT_PUBLIC_HEADLINE_ENDPOINT,
    NEXT_PUBLIC_ABOUT_ENDPOINT: process.env.NEXT_PUBLIC_ABOUT_ENDPOINT,
    NEXT_PUBLIC_EDUCATION_ENDPOINT: process.env.NEXT_PUBLIC_EDUCATION_ENDPOINT,
    NEXT_PUBLIC_EXPERIENCE_ENDPOINT: process.env.NEXT_PUBLIC_EXPERIENCE_ENDPOINT,
    NEXT_PUBLIC_SKILLS_ENDPOINT: process.env.NEXT_PUBLIC_SKILLS_ENDPOINT,
    NEXT_PUBLIC_CONTACT_ENDPOINT: process.env.NEXT_PUBLIC_CONTACT_ENDPOINT,

    NEXT_PUBLIC_ACTIVITY_ENDPOINT: process.env.NEXT_PUBLIC_ACTIVITY_ENDPOINT,
    NEXT_PUBLIC_FEED_ENDPOINT: process.env.NEXT_PUBLIC_FEED_ENDPOINT,
    NEXT_PUBLIC_COMMENTS_ENDPOINT: process.env.NEXT_PUBLIC_COMMENTS_ENDPOINT,
    NEXT_PUBLIC_REPORTS_ENDPOINT: process.env.NEXT_PUBLIC_REPORTS_ENDPOINT,

    NEXT_PUBLIC_MENTORSHIP_ENDPOINT: process.env.NEXT_PUBLIC_MENTORSHIP_ENDPOINT,
    NEXT_PUBLIC_MENTOR_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_MENTOR_CREATE_ENDPOINT,
    NEXT_PUBLIC_MENTOR_BY_ID_ENDPOINT: process.env.NEXT_PUBLIC_MENTOR_BY_ID_ENDPOINT,
    NEXT_PUBLIC_MENTOR_BY_USER_ENDPOINT: process.env.NEXT_PUBLIC_MENTOR_BY_USER_ENDPOINT,
    NEXT_PUBLIC_ALL_MENTORS_ENDPOINT: process.env.NEXT_PUBLIC_ALL_MENTORS_ENDPOINT,
    NEXT_PUBLIC_MENTOR_UPDATE_ENDPOINT: process.env.NEXT_PUBLIC_MENTOR_UPDATE_ENDPOINT,

    NEXT_PUBLIC_AVAILABILITY_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_CREATE_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_GET_ALL_DB_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_GET_ALL_DB_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_BULK_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_BULK_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_MENTOR_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_MENTOR_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_UPDATE_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_UPDATE_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_DELETE_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_DELETE_ENDPOINT,
    NEXT_PUBLIC_AVAILABILITY_STATS_ENDPOINT: process.env.NEXT_PUBLIC_AVAILABILITY_STATS_ENDPOINT,

    NEXT_PUBLIC_SESSIONS_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_ENDPOINT,
    NEXT_PUBLIC_SESSIONS_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_CREATE_ENDPOINT,
    NEXT_PUBLIC_SESSIONS_GET_ALL_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_GET_ALL_ENDPOINT,
    NEXT_PUBLIC_SESSIONS_GET_ALL_DB_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_GET_ALL_DB_ENDPOINT,
    NEXT_PUBLIC_SESSIONS_MENTOR_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_MENTOR_ENDPOINT,
    NEXT_PUBLIC_SESSIONS_BOOK_ENDPOINT: process.env.NEXT_PUBLIC_SESSIONS_BOOK_ENDPOINT,

    NEXT_PUBLIC_NOTIFICATIONS_ENDPOINT: process.env.NEXT_PUBLIC_NOTIFICATIONS_ENDPOINT,
    NEXT_PUBLIC_NOTIFICATIONS_ALL_MARKED_READ_ENDPOINT: process.env.NEXT_PUBLIC_NOTIFICATIONS_ALL_MARKED_READ_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUPS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUPS_ENDPOINT,
    NEXT_PUBLIC_MY_STUDY_GROUPS_ENDPOINT: process.env.NEXT_PUBLIC_MY_STUDY_GROUPS_ENDPOINT,
    NEXT_PUBLIC_CREATE_STUDY_GROUP_ENDPOINT: process.env.NEXT_PUBLIC_CREATE_STUDY_GROUP_ENDPOINT,
    NEXT_PUBLIC_TOP_RANKED_STUDY_GROUPS_ENDPOINT: process.env.NEXT_PUBLIC_TOP_RANKED_STUDY_GROUPS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_MEMBER_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_MEMBER_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_GROUPS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_GROUPS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_POPULAR_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_POPULAR_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_TRENDING_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_TRENDING_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_RECOMMENDED_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_RECOMMENDED_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_CATEGORY_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_CATEGORY_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_AVAILABLE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_AVAILABLE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUEST_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUEST_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_MESSAGES_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_MESSAGES_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_FILES_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_FILES_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SEARCH_TAGS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SEARCH_TAGS_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_TIMER_START_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_START_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_PAUSE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_PAUSE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_RESUME_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_RESUME_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_STOP_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_STOP_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_CANCEL_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_CANCEL_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_ACTIVE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_ACTIVE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_TODAY_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_TODAY_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TIMER_STATS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TIMER_STATS_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_GOALS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_GOALS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_GOAL_COMPLETE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_GOAL_COMPLETE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_GOAL_INCOMPLETE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_GOAL_INCOMPLETE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_GOALS_ACTIVE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_GOALS_ACTIVE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_GOALS_STATS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_GOALS_STATS_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_USER_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_USER_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_GROUP_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_GROUP_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_PERFORMANCE_ANALYTICS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_PERFORMANCE_ANALYTICS_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_TASKS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASKS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TASK_COMPLETE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASK_COMPLETE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TASK_INCOMPLETE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASK_INCOMPLETE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TASKS_STATS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASKS_STATS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_TASKS_UPCOMING_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASKS_UPCOMING_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_STATISTICS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_STATISTICS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_ANALYTICS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DASHBOARD_ANALYTICS_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_TASKS_OVERDUE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_TASKS_OVERDUE_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_MY_REQUESTS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_MY_REQUESTS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_GROUP_REQUESTS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_GROUP_REQUESTS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_RESPOND_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_JOIN_REQUESTS_RESPOND_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_CHAT_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_CHAT_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_CHAT_MESSAGE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_CHAT_MESSAGE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_FILES_UPLOAD_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_FILES_UPLOAD_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ANSWER_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_ANSWER_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_SEARCH_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_SEARCH_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_MY_DOUBTS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_MY_DOUBTS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_CATEGORY_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_CATEGORY_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_DOUBTS_USER_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_GROUP_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_LIVE_ROOMS_GROUP_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CHECK_IN_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CHECK_IN_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_AUTO_MARK_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_AUTO_MARK_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_GROUP_STATS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_GROUP_STATS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_USER_STATS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_USER_STATS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_STATUS_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_STATUS_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_PERCENTAGE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_PERCENTAGE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_HISTORY_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_HISTORY_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CALENDAR_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_ATTENDANCE_CALENDAR_ENDPOINT,

    NEXT_PUBLIC_STUDY_GROUP_SHARE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SHARE_ENDPOINT,
    NEXT_PUBLIC_STUDY_GROUP_SHARE_VALIDATE_ENDPOINT: process.env.NEXT_PUBLIC_STUDY_GROUP_SHARE_VALIDATE_ENDPOINT,

    NEXT_PUBLIC_COMPANY_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_ENDPOINT,
    NEXT_PUBLIC_COMPANY_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_CREATE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_BY_ID_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_BY_ID_ENDPOINT,
    NEXT_PUBLIC_COMPANY_UPDATE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_UPDATE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_DELETE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_DELETE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_GET_ALL_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_GET_ALL_ENDPOINT,
    NEXT_PUBLIC_COMPANY_COMPANIES_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_COMPANIES_ENDPOINT,

    NEXT_PUBLIC_COMPANY_ANALYTICS_DASHBOARD_V2_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_ANALYTICS_DASHBOARD_V2_ENDPOINT,
    NEXT_PUBLIC_COMPANY_ANALYTICS_COMPANY_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_ANALYTICS_COMPANY_ENDPOINT,
    NEXT_PUBLIC_COMPANY_ANALYTICS_TOP_POSTS_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_ANALYTICS_TOP_POSTS_ENDPOINT,

    NEXT_PUBLIC_COMPANY_EMPLOYEES_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EMPLOYEES_ENDPOINT,
    NEXT_PUBLIC_COMPANY_EVENTS_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EVENTS_CREATE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_EVENTS_GET_ALL_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EVENTS_GET_ALL_ENDPOINT,
    NEXT_PUBLIC_COMPANY_ANALYTICS_TRACK_USER_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_ANALYTICS_TRACK_USER_ENDPOINT,
    NEXT_PUBLIC_COMPANY_EMPLOYEE_GET_BY_ID_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EMPLOYEE_GET_BY_ID_ENDPOINT,
    NEXT_PUBLIC_COMPANY_EMPLOYEES_COMPANIES_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EMPLOYEES_COMPANIES_ENDPOINT,
    NEXT_PUBLIC_COMPANY_EMPLOYEE_ADVOCACY_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_EMPLOYEE_ADVOCACY_ENDPOINT,

    NEXT_PUBLIC_COMPANY_POSTS_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_ENDPOINT,
    NEXT_PUBLIC_COMPANY_POSTS_CREATE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_CREATE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_POSTS_COMPANY_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_COMPANY_ENDPOINT,
    NEXT_PUBLIC_COMPANY_POSTS_DELETE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_DELETE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_POSTS_LIKE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_LIKE_ENDPOINT,
    NEXT_PUBLIC_COMPANY_POSTS_UNLIKE_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_POSTS_UNLIKE_ENDPOINT,

    NEXT_PUBLIC_COMPANY_CONNECTIONS_FOLLOW_ENDPOINT: process.env.NEXT_PUBLIC_COMPANY_CONNECTIONS_FOLLOW_ENDPOINT,

    NEXT_PUBLIC_CONNECTIONS_REQUESTS_ENDPOINT: process.env.NEXT_PUBLIC_CONNECTIONS_REQUESTS_ENDPOINT,
    NEXT_PUBLIC_FOLLOW_ENDPOINT: process.env.NEXT_PUBLIC_FOLLOW_ENDPOINT,
    NEXT_PUBLIC_CONNECTIONS_REQUESTS_USER_ENDPOINT: process.env.NEXT_PUBLIC_CONNECTIONS_REQUESTS_USER_ENDPOINT,
    NEXT_PUBLIC_CONNECTIONS_CONNECTION_USER_ENDPOINT: process.env.NEXT_PUBLIC_CONNECTIONS_CONNECTION_USER_ENDPOINT,
    NEXT_PUBLIC_CONNECTIONS_USER_ENDPOINT: process.env.NEXT_PUBLIC_CONNECTIONS_USER_ENDPOINT,
    NEXT_PUBLIC_FOLLOW_COUNTS_ENDPOINT: process.env.NEXT_PUBLIC_FOLLOW_COUNTS_ENDPOINT,

    NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPONT: process.env.NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPONT,
    NEXT_PUBLIC_MESSAGES_DIRECT_ENDPOINT: process.env.NEXT_PUBLIC_MESSAGES_DIRECT_ENDPOINT,
    NEXT_PUBLIC_MESSAGES_MESSAGES_ENDPOINT: process.env.NEXT_PUBLIC_MESSAGES_MESSAGES_ENDPOINT,
    NEXT_PUBLIC_MESSAGES_REACT_ENDPOINT: process.env.NEXT_PUBLIC_MESSAGES_REACT_ENDPOINT,
    NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPOINT: process.env.NEXT_PUBLIC_MESSAGES_CONVERSATIONS_ENDPOINT,
    NEXT_PUBLIC_GET_USERS_BULK_ENDPOINT: process.env.NEXT_PUBLIC_GET_USERS_BULK_ENDPOINT,

    NEXT_PUBLIC_VERIFY_EMAIL_SEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_SEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_VERIFY_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_VERIFY_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_RESEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_RESEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_STATUS_CHECK_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_STATUS_CHECK_ENDPOINT,

    NEXT_PUBLIC_VERIFY_PHONE_SEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_PHONE_SEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_PHONE_VERIFY_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_PHONE_VERIFY_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_PHONE_RESEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_PHONE_RESEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_PHONE_STATUS_CHECK_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_PHONE_STATUS_CHECK_ENDPOINT,

    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_SEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_SEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_VERIFY_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_VERIFY_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_RESEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_RESEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_STATUS_CHECK_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_IDENTITY_AADHAAR_STATUS_CHECK_ENDPOINT,

    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_SEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_SEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_VERIFY_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_VERIFY_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_RESEND_OTP_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_RESEND_OTP_ENDPOINT,
    NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_STATUS_CHECK_ENDPOINT: process.env.NEXT_PUBLIC_VERIFY_EMAIL_COMPANY_EMAIL_STATUS_CHECK_ENDPOINT,

    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
    NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET,
    NEXT_PUBLIC_CLOUDINARY_BASE_URL: process.env.NEXT_PUBLIC_CLOUDINARY_BASE_URL,

    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_APP_ENV: process.env.NEXT_PUBLIC_APP_ENV,

    NEXT_PUBLIC_MAX_PHOTO_SIZE: process.env.NEXT_PUBLIC_MAX_PHOTO_SIZE,
    NEXT_PUBLIC_MAX_COVER_SIZE: process.env.NEXT_PUBLIC_MAX_COVER_SIZE,
    NEXT_PUBLIC_MAX_VIDEO_SIZE: process.env.NEXT_PUBLIC_MAX_VIDEO_SIZE,
    NEXT_PUBLIC_ALLOWED_IMAGE_TYPES: process.env.NEXT_PUBLIC_ALLOWED_IMAGE_TYPES,

    NEXT_PUBLIC_DEFAULT_PAGE_SIZE: process.env.NEXT_PUBLIC_DEFAULT_PAGE_SIZE,
    NEXT_PUBLIC_MAX_PAGE_SIZE: process.env.NEXT_PUBLIC_MAX_PAGE_SIZE,

    NEXT_PUBLIC_ENABLE_MASTERCLASSES: process.env.NEXT_PUBLIC_ENABLE_MASTERCLASSES,
    NEXT_PUBLIC_ENABLE_COMPARE: process.env.NEXT_PUBLIC_ENABLE_COMPARE,
    NEXT_PUBLIC_ENABLE_FIND_MENTOR: process.env.NEXT_PUBLIC_ENABLE_FIND_MENTOR,
    NEXT_PUBLIC_ENABLE_NOTIFICATIONS: process.env.NEXT_PUBLIC_ENABLE_NOTIFICATIONS,

    NEXT_PUBLIC_GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,

    NEXT_PUBLIC_RAZORPAY_KEY_ID: process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,

    NEXT_PUBLIC_GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    NEXT_PUBLIC_LINKEDIN_CLIENT_ID: process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID,
  },
}
export default nextConfig